{
	"ExceptionType": "Dapper.Repository.Exceptions.RepositoryException",
	"Message": "Can\u0027t save this row in the \u0027dbo.Appointment\u0027 table because the value \u002716, 7, 2025-05-19, 64771\u0027 already exists and duplicates are not allowed.",
	"Locations": [
		{
			"MethodName": "SaveAsync",
			"Filename": "Hs5/Hs5.Services/Repositories/BaseRepository.cs",
			"LineNumber": 32
		},
		{
			"MethodName": "SaveOrUpdateAsync",
			"Filename": "Hs5/Hs5.Services/Repositories/BaseRepository.cs",
			"LineNumber": 129
		}
	],
	"ErrorId": "153fc7ed34eee9e149d21a761a8d24a4"
}